from django.conf.urls import patterns, url
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from geonode.apps.views import AppListView
# from .views import GroupDetailView, GroupActivityView
# from .views import AppDetailView

urlpatterns = patterns('geonode.apps.views',
                       url(r'^$',
                           login_required(AppListView.as_view(template_name='apps/app_list.html')),
                           name="contractor_service_list"),

                       url(r"^member/(?P<app_id>[-\d+]+)/(?P<username>[^/]*)/$",
                           "member_detail",
                           name="app_member_detail"),                       
                       url(r'^resource/share/(?P<app_id>[-\d]+)$',
                           'resource_share',
                           name="app_resource_share"),                       
                       url(r'^create/$',
                           'app_create',
                           name="contractor_service_create",
                           kwargs={'is_service':True}),
                       url(r'^(?P<slug>[-\w]+)/$',
                            'app_detail',
                            name='app_detail'),
                       url(r'^(?P<slug>[-\w]+)/update/$',
                           'app_update',
                           name='app_update'),
                       # url(r'^app/(?P<slug>[-\w]+)/members/$',
                       #     'app_members',
                       #     name='app_members'),
                       # url(r'^group/(?P<slug>[-\w]+)/invite/$',
                       #     'group_invite',
                       #     name='group_invite'),
                       # url(r'^group/(?P<slug>[-\w]+)/members_add/$',
                       #     'group_members_add',
                       #     name='group_members_add'),
                       url(r'^(?P<slug>[-\w]+)/unlink/(?P<username>.+)$',
                           'app_member_unlink',
                           name='app_member_unlink'),
                       url(r'^(?P<slug>[-\w]+)/remove/$',
                           'app_remove',
                           name='app_remove'),
                       url(r'^(?P<slug>[-\w]+)/link/(?P<username>.+)$',
                           'app_member_link',
                           name='app_member_link'),
                       # url(r'^group/[-\w]+/invite/(?P<token>[\w]{40})/$',
                       #     'group_invite_response',
                       #     name='group_invite_response'),
                       # url(r'^group/(?P<slug>[-\w]+)/activity/$',
                       #     GroupActivityView.as_view(),
                       #     name='group_activity'),
                       )
